# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on:
  workflow_dispatch:
    inputs:
      modtag:
        required: false
        description: "Mod Version: Create Nuclear for Release"
      name:
        required: true
        default: CreateNuclear
        description: Mod file name
      version: 
        required: false
        description: Mod version
      version-type:
        required: true
        default: alpha
        description: Version type
      changelog:
        required: true
        default: No change log
        description: Changelog for version

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [[ubuntu-22.04]]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo ${{ github.ref_name }}
          name=$(git --no-pager tag --sort=creatordate --merged main | tail -2 | head -1)
          echo "previousTag: $name"
